# Generated by Django 4.2.10 on 2026-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_analysishistory_codeexecution_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/'),
        ),
    ]
