# Generated by Django 4.2.10 on 2026-04-07 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_last_login_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_executions', models.IntegerField(default=0)),
                ('successful_executions', models.IntegerField(default=0)),
                ('failed_executions', models.IntegerField(default=0)),
                ('total_execution_time', models.FloatField(default=0.0)),
                ('average_execution_time', models.FloatField(default=0.0)),
                ('languages_used', models.JSONField(default=dict)),
                ('last_execution_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Stats',
                'verbose_name_plural': 'Execution Stats',
            },
        ),
    ]
