# Generated by Django 4.2.10 on 2026-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_executionstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analysishistory',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
